### PR TITLE
Added current tax rate when shipping cost are excluded

### PR DESCRIPTION
**Pull request by riker09**
In my point of view there is no reason why the current tax rate should not be displayed when the shipping cost are excluded.

### CODE REVIEW

**Comment by sibbl** [comment]
Already 3 months and nothing happened... Annoying bug. Should be merged asap!

**Comment by sprankhub** [comment]
Please mind that GermanSetup is now [MageSetup](https://github.com/firegento/firegento-magesetup). MageSetup is developed and maintained, GermanSetup is not any more.

**Comment by sibbl** [comment]
Thanks for the hint, seems like I missed this last month :)

**Comment by therouv** [comment]
Closing this pull request as of MageSetup is now the current module.

**Pull request closed without merging**
